# Generated by Django 3.0.4 on 2020-04-10 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scrape', '0003_auto_20200410_0314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='shoppinglist',
            new_name='shoppingList',
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shoppingList', to=settings.AUTH_USER_MODEL),
        ),
    ]
